### ISSUE TITLE
Help! Data file may be corrupted!  I am stuck!

### ISSUE THREAD

**Issue by mikeda100** [LianjiaTech/BELLE#189]
HI there,

I downloaded the ELLE-LLaMA-13B-2M-enc model from HuggingFace.

And when I ran the "decrypting" process, I got the following error messages. 

But I made sure that the md5sums match the ones you've posted in the README.MD on the HuggingFace website. 

That's to say, I made sure the md5sums are corrected, before I moved to the "decrypting" step.

Decrypting file /DownloadedSoftwares/BELLE/models/BELLE-LLaMA-13B-2M-enc/config.json.e366f0c901ee336cb921450f975b3e3c5e32874035d227f4263dbcb5d966b822.enc with 2 workers
Writing final chunks...
Error: Checksums do not match. The file may be corrupted.

---------------------

And when I reran the "decrypting" process, more files had been declared as "Error: Checksums do not match. The file may be corrupted." 

-----------------------

As the result, I ended up with the following files after the "decrypting": note the files with 0 sizes. I have reran these processes for quite a number of times and couldn't solve the problem.

-rw-r--r-- 1 root root          0 4月  14 13:25 config.json
-rw-r--r-- 1 root root        137 4月  14 13:25 generation_config.json
-rw-r--r-- 1 root root        621 4月  14 13:52 md5sum-merged-model-calculated.txt
-rw-r--r-- 1 root root        607 4月  14 13:50 md5sum-merged-model-theoretical.txt
-rw-r--r-- 1 root root 9948722999 4月  14 13:31 pytorch_model-00001-of-00003.bin
-rw-r--r-- 1 root root 9904159487 4月  14 13:37 pytorch_model-00002-of-00003.bin
-rw-r--r-- 1 root root 6178979924 4月  14 13:41 pytorch_model-00003-of-00003.bin
-rw-r--r-- 1 root root      33444 4月  14 13:41 pytorch_model.bin.index.json
-rw-r--r-- 1 root root          0 4月  14 13:41 special_tokens_map.json
-rw-r--r-- 1 root root          0 4月  14 13:41 tokenizer_config.json
-rw-r--r-- 1 root root     499723 4月  14 13:41 tokenizer.model

Can you please help me?

Thanks a lot!

**Comment by mabaochang** [comment]
I have fixed the decrypt.py ，you can use the new code. @mikeda100

**Comment by mabaochang** [comment]
previous code from pointer-llma use multiprocessing, I have remove it.

**Comment by mikeda100** [comment]
Now it worked!
Thanks a lot!
(but it is a lot slower now :=()
-----------------------------------------------------
-rw-r--r-- 1 root root        472 4月  14 14:17 config.json
-rw-r--r-- 1 root root        137 4月  14 14:17 generation_config.json
-rw-r--r-- 1 root root        621 4月  14 13:52 md5sum-merged-model-calculated.txt
-rw-r--r-- 1 root root        607 4月  14 13:50 md5sum-merged-model-theoretical.txt
-rw-r--r-- 1 root root 9948722999 4月  14 14:30 pytorch_model-00001-of-00003.bin
-rw-r--r-- 1 root root 9904159487 4月  14 14:41 pytorch_model-00002-of-00003.bin
-rw-r--r-- 1 root root 6178979924 4月  14 14:49 pytorch_model-00003-of-00003.bin
-rw-r--r-- 1 root root      33444 4月  14 14:49 pytorch_model.bin.index.json
-rw-r--r-- 1 root root          2 4月  14 14:49 special_tokens_map.json
-rw-r--r-- 1 root root        141 4月  14 14:49 tokenizer_config.json
-rw-r--r-- 1 root root     499723 4月  14 14:49 tokenizer.model

**Comment by muziyongshixin** [comment]
我更新后还是无法运行，我下载的原始的llama-13B的模型有2个pth文件，但是执行脚本输入只指定了一个，是否有问题？是需要先将原始的两个pth文件合并成同一个吗？

mkdir: cannot create directory ‘/mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-full_model’: File exists
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/config.json.e366f0c901ee336cb921450f975b3e3c5e32874035d227f4263dbcb5d966b822.enc
Writing final chunks...
Decryption completed.
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/generation_config.json.fd7ff399e5568cc21a0a8414f43df88ef7c424995b9b97a90563165d2cf79efd.enc
Writing final chunks...
Decryption completed.
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/pytorch_model-00001-of-00003.bin.5abb160ecbd441c6a1fbe00a9eaa194ee0bd8cd75850c24f503336bd29f0dc45.enc
Writing final chunks...
Error: Checksums do not match. The file may be corrupted.
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/pytorch_model-00002-of-00003.bin.46a0e748edff9f0f82aa5f3e721e80e0f342f3d03dc47d0ec6514ea78a585320.enc
Writing final chunks...
Error: Checksums do not match. The file may be corrupted.
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/pytorch_model-00003-of-00003.bin.ec6e4d45dc4c51f2b9abff5ea9840f06f633e065cdf574b71e96366c26a01578.enc
Writing final chunks...
Error: Checksums do not match. The file may be corrupted.
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/pytorch_model.bin.index.json.72e91e29282dae48ea5562fcf4d6ca0d5a9c2a30ebc8d67174a19e192552a20b.enc
Writing final chunks...
Error: Checksums do not match. The file may be corrupted.
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/README.md
Traceback (most recent call last):
  File "/mnt/bn/vgraph/biz_llm/biz_llm/BELLE/models/decrypt.py", line 122, in <module>
    main(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/mnt/bn/vgraph/biz_llm/biz_llm/BELLE/models/decrypt.py", line 67, in main
    with open(output_file, "wb") as out_file:
IsADirectoryError: [Errno 21] Is a directory: '/mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-full_model/'
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/special_tokens_map.json.44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a.enc
Writing final chunks...
Decryption completed.
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/tokenizer_config.json.ef7ef410b9b909949e96f172b17cbf7c68b11761c632715fa05a6088c0c2b9ac.enc
Writing final chunks...
Decryption completed.
Decrypting file /mnt/bn/vgraph/biz_llm/biz_llm/BELLE/train/trained_models/BELLE-LLaMA-13B-2M-enc/tokenizer.model.9e556afd44213b6bd1be2b850ebbbd98f5481437a8021afaf58ee7fb1818d347.enc
Writing final chunks...
Error: Checksums do not match. The file may be corrupted.

**Comment by muziyongshixin** [comment]
> ## Now it worked!
> Thanks a lot!
> (but it is a lot slower now :=()
> -rw-r--r-- 1 root root 472 4月 14 14:17 config.json -rw-r--r-- 1 root root 137 4月 14 14:17 generation_config.json -rw-r--r-- 1 root root 621 4月 14 13:52 md5sum-merged-model-calculated.txt -rw-r--r-- 1 root root 607 4月 14 13:50 md5sum-merged-model-theoretical.txt -rw-r--r-- 1 root root 9948722999 4月 14 14:30 pytorch_model-00001-of-00003.bin -rw-r--r-- 1 root root 9904159487 4月 14 14:41 pytorch_model-00002-of-00003.bin -rw-r--r-- 1 root root 6178979924 4月 14 14:49 pytorch_model-00003-of-00003.bin -rw-r--r-- 1 root root 33444 4月 14 14:49 pytorch_model.bin.index.json -rw-r--r-- 1 root root 2 4月 14 14:49 special_tokens_map.json -rw-r--r-- 1 root root 141 4月 14 14:49 tokenizer_config.json -rw-r--r-- 1 root root 499723 4月 14 14:49 tokenizer.model

Hi, I am wondering wheather there are 2 pth file in the original llama-13B checkpoint dir? I run the newest script still get  `Checksums do not match. The file may be corrupted.` error. I dont know what is wrong.

**Comment by mabaochang** [comment]
> 

你可以查看下几个大文件下载后的md5值，我现在怀疑没有安装git lfs，所以大文件没有下载全
